### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by jerriclynsjohn** [rixo/svench-component-template#1]
I tried using this template but it is throwing a build error. after installing the dependencies I ran `npm run svench`, but it was of no use.

```bash
[!] (plugin svench:after) TypeError: Cannot read property 'id' of undefined
src\a_directory_section.svench\my_page.svench.svx
TypeError: Cannot read property 'id' of undefined
    at Object.transform (D:\CodeBase\TestBase\Svelte\svelte-lib\node_modules\svench\rollup.js:32140:65)
    at D:\CodeBase\TestBase\Svelte\svelte-lib\node_modules\rollup\dist\shared\rollup.js:18614:25
```

**Comment by happybeing** [comment]
That might be node version, can't find it in the READMEs, but I think it requires node >= 12.

EDIT: not v10 as first stated but v12, see https://github.com/rixo/svench/issues/4#issuecomment-630746195

**Comment by rixo** [comment]
Thanks for reporting. Sorry for taking so long to come back at this, I've been a little pressed by time lately...

I've just run a few tests and indeed it seems that this template is broken with last Svelte versions. My tests seem to indicate that it is broken from Svelte v3.24+.

I don't get the exact same error as you with latest Svelte versions... More like blank page with no console error (gloups). Would you be so kind as to test with Svelte 3.23 and see if it solves your own error too?

Also, as mentioned by @theWebalyst, Svench expects a pretty recent Node version. I'm running Node 12 currently, so it might worth testing with that too. (I'm planning to specify the required Node version eventually and, maybe, run the code through Babel to lessen it if it proves to be too much for people.)

**Comment by rixo** [comment]
OK I finally was able to fix the blank page error I was getting with latest versions of Svelte. Turns out it was a bug in `svelte-hmr` introduced by Svelte 3.24.1. It should be fixed by installing `rollup-plugin-svelte-hot@latest` (0.11.0) and `svench@next` (0.0.10-7).

@jerriclynsjohn Does upgrading to the aforementioned versions also fix the error you're encountering?

**Comment by rixo** [comment]
Closing due to inactivity. This problem is deemed fixed. You're welcome to reopen if you still have the issue in the next version.
